# SPDX-FileCopyrightText: 2026 Blender Foundation
#
# SPDX-License-Identifier: GPL-2.0-or-later

include("${CMAKE_CURRENT_LIST_DIR}/blender_release.cmake")

set(WITH_DLSS ON CACHE BOOL "" FORCE)
set(WITH_DLSS_FRAME_GENERATION ON CACHE BOOL "" FORCE)
set(WITH_CYCLES_CUDA_BINARIES ON CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_CUDA ON CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_OPTIX ON CACHE BOOL "" FORCE)
set(CYCLES_CUDA_BINARIES_ARCH "sm_89;sm_120" CACHE STRING "" FORCE)
set(WITH_BUILDINFO ON CACHE BOOL "" FORCE)
